# Serveur principal (par défaut)
server {
    listen 8080;
    # host 127.0.0.1;
    # server_name localhost;
    # 
    # # Page d'erreur 404
    # error_page 505 404 /404.html;
    # # 
    # # # Limite taille requête à 1MB
    # client_max_body_size 1048576;
    # # 
    # # # Route principale
    location / {
        root ./www;
        index  index.html;
        allow_methods GET POST;
        autoindex on;
    }
    location /hello {
        root ./www;
        # index index.html;
        autoindex on;
        allow_methods GET POST;
    }
    # # 
    # # # Route pour upload
    # location /upload {
    #     root ./www/upload;
    #     allow_methods GET POST DELETE;
    #     upload_store ./www/upload/files/;
    #     upload_enable on;
    # }
}


# Serveur secondaire
server{
	listen 8181;

    location /python {
        root ./www/;
        index testcgi.html;
        allow_methods GET POST;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
    }
}
#
# server{
# 	listen 9090;
# }
