# Serveur principal (par défaut)
server {
    listen 8080;
    # host 127.0.0.1;
    # server_name localhost;
    # 
    # # Page d'erreur 404
    # error_page 505 404 /404.html;
    # # 
    # # # Limite taille requête à 1MB
    # clientMaxBodySize 1048576;
    # # 
    # # # Route principale
    location / {
        root ./www;
        index  index.html post.html delete.html cgi.html;
        allowedMethods GET POST;
        autoindex on;
    }
    location /hello {
        root ./www;
       #index index.html;
        autoindex on;
        allowedMethods GET POST;
    }

    location /python-cgi/ {
        root ./cgi_examples;
        allowedMethods GET POST;
        cgiExtension .py;
        cgiPath /usr/bin/python3;
        autoindex on;
    }

    location /perl-cgi/ {
        root ./cgi_examples;
        allowedMethods GET POST;
        cgiExtension .pl;
        cgiPath /usr/bin/perl;
        autoindex on;
    }

    # # 
    # # # Route pour upload
    # location /upload {
    #     root ./www/upload;
    #     allowedMethods GET POST DELETE;
    #     uploadStore ./www/upload/files/;
    #     uploadEnabled on;
    # }
}


# Serveur secondaire
server{
	listen 8181;

    location /python {
        root ./www/;
        index testcgi.html;
        allowedMethods GET POST;
        cgiExtension .py;
        cgiPath /usr/bin/python3;
    }
}
#
# server{
# 	listen 9090;
# }
