# Serveur principal (par défaut)
server {
    listen 8080;
    error_page 404 ./www/error_pages/404.html;
    # Limite taille requête à 1MB
    clientMaxBodySize 1048576;

    # Route principale
    location / {
        root ./www;
        index  index.html post.html delete.html cgi.html;
        allowedMethods GET POST DELETE;
        autoindex on;
    }

    location /upload {
        root ./www;
        allowedMethods POST;
        uploadEnabled on;
        uploadStore ./www/uploads/;
    }

    location /uploads/ {
        allowedMethods GET DELETE;
        root ./www/uploads;
    }

    location /hello {
        root ./www;
       #index index.html;
        autoindex on;
        allowedMethods GET POST;
    }

    location /python-cgi/ {
        root ./cgi_examples;
        allowedMethods GET POST;
        cgiExtension .py;
        cgiPath /usr/bin/python3;
        autoindex on;
    }

    location /bash-cgi/ {
        root ./cgi_examples;
        allowedMethods GET POST;
        cgiExtension .sh;
        # cgiPath /usr/bin/bash; # for Linux
        cgiPath /bin/bash; # for Mac
        autoindex on;
    }

    location /bash-cgi/ {
        root ./cgi_examples;
        allowedMethods GET POST;
        cgiExtension .sh;
        cgiPath /usr/bin/bash;
        autoindex on;
    }
}


# Serveur secondaire
# server{
# 	listen 8181;

#     location /python {
#         root ./www/;
#         index testcgi.html;
#         allowedMethods GET POST;
#         cgiExtension .py;
#         cgiPath /usr/bin/python3;
#     }
# }
#
# server{
# 	listen 9090;
# }
